# Layout
Layout/ArgumentAlignment:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Lint
Lint/HeredocMethodCallPosition:
  Enabled: true
Lint/NumberConversion:
  Enabled: true
Lint/UnusedBlockArgument:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false

# Metrics
Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Max: 50
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    # Rake
    - '**/Rakefile'
    - '**/*.rake'
    # RSpec
    - 'spec/**/*.rb'
    # Rails
    - 'config/routes.rb'
Metrics/BlockNesting:
  Max: 10
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/MethodLength:
  Max: 100
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/ModuleLength:
  Max: 300
  CountAsOne: ['array', 'hash', 'heredoc']
Metrics/ParameterLists:
  Max: 20
Metrics/PerceivedComplexity:
  Max: 30

# Naming
Naming/VariableNumber:
  Enabled: false

# Style
Style/AccessorGrouping:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/RedundantSelf:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
